spring:
  application:
   name: spring-security-learning
  security:
    user:
      name: "test"
      password: "test"
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/SpringSecLabRealm/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:springSecurityDB}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root@1234}

server:
  port: 9001

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{dd/MM/yyyy HH:mm:ss.SSS}) %blue(%-5level) %cyan(@project.artifactId@:@project.version@ %X{traceId} %X{spanId}) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
  level:
    org:
      springframework:
        security: TRACE