spring:
  application:
   name: spring-security-learning

server:
  port: 9001

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{dd/MM/yyyy HH:mm:ss.SSS}) %blue(%-5level) %cyan(@project.artifactId@:@project.version@ %X{traceId} %X{spanId}) %red([%thread]) %yellow(%logger{15}) - %msg%n}"